# Generated by Django 4.2.7 on 2024-02-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_alter_cita_empleado_alter_cita_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.CharField(max_length=50),
        ),
    ]
