# Generated by Django 4.2.7 on 2024-02-07 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_cita_empleado_alter_cita_servicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_empleado', to='agenda.empleado'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_servicio', to='agenda.servicio'),
        ),
    ]
