# Generated by Django 4.2.5 on 2024-02-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_usuario_password_reset_token_alter_cita_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=128),
        ),
    ]
